### PR TITLE
Increase the cache timeout and add a NOCACHE option

### PR DESCRIPTION
**Pull request by martinthomson**
I find myself fetching more often than is ideal.

### CODE REVIEW

**Comment by cabo** [comment]
I don't think that there is a "good" value for the cache lifetime.  The current value of two hours was arrived at while working on drafts in a dynamic environment, i.e., referencing other drafts that change as well.    Two hours is mostly on the safe side because this is about the time one needs to react to changes in other drafts (you can always force a refetch by deleting the cache entry).   If you only ever reference old drafts, a much longer cache lifetime would indeed be an improvement.  But the right solution would:

* distinguish dynamic (reference.I-D.ietf...) from essentially immutable (reference.RFC.0020.xml) references
* use cache validation instead of simply refetching after timeout

The latter point would also require keeping metadata around (e.g., Etags), making cache sharing with XML2RFC a bit harder.  (I would model the metadata after https://github.com/tigris/open-uri-cached/blob/master/lib/open-uri/cached.rb ).

For people who are keeping rsync copies around, being able to point to a set of rsync directories (with different semantics than KRAMDOWN_REFCACHEDIR) would also be helpful.

Hmm.

**Comment by martinthomson** [comment]
I agree that this is a rathole that is as big as you like.  As you say, fetching RFCs often is pointless, and I-Ds might change faster than any limit.

I'm looking to ship 4 drafts in quic(heh) succession.  That's going to need cache-busting no matter what the model.  Nothing that the server says (Cache-Control, etag, whatever) is going to save you from needing an override.

How about this: 1 hours for I-Ds by default, 1 week for RFCs.  Override the default with KRAMDOWN_REFCACHETTL=<n> (which is global because anything else is more code).

**Comment by cabo** [comment]
I went ahead and defined three environment variables:

```
+      KRAMDOWN_OFFLINE = ENV["KRAMDOWN_OFFLINE"]
+      KRAMDOWN_REFCACHE_REFETCH = ENV["KRAMDOWN_REFCACHE_REFETCH"]
+      KRAMDOWN_REFCACHETTL = (e = ENV["KRAMDOWN_REFCACHETTL"]) ? e.to_i : 3600
```

OFFLINE completely switches off fetching (which might lead to an error if the file isn't there).  REFETCH fetches everything, not applying TTLs (I like that better than NOCACHE, because the cache *is* being populated).  As you proposed, REFCACHETTL is the default cache TTL, where RFCs get a week instead and the autogenerated IANA and DOI get a day (which is their autogeneration cache lifetime).

**Comment by cabo** [comment]
Covered in 1.0.42

**Pull request closed without merging**
